name: quickshop
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.3.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  fonts:
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logo/
    - assets/fonts/
