name: 'Clean Github Actions Runner'
description: 'Remove unneeded packages and clean up disk space on the Github Actions runner'
inputs:
  inspect:
    description: 'Whether to inspect disk usage in key folders before cleaning. This is helpful for debugging this action, but adds 30-60s to the run time.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Get current disk free space
      shell: bash
      run: |
        start_time=$SECONDS

        echo "Getting disk free space"
        df -h

        echo "Disk free space check took $(($SECONDS - $start_time)) seconds"

    - name: Inspect disk usage
      shell: bash
      if: ${{ inputs.inspect == 'true' }}
      run: |
        start_time=$SECONDS

        echo "Getting /usr/share disk usage"
        du -shc /usr/share/* | sort -hr | head -n 10

        echo "Getting /usr/local/share disk usage"
        du -shc /usr/local/share/* | sort -hr | head -n 10

        echo "Getting /usr/local/lib disk usage"
        du -shc /usr/local/lib/* | sort -hr | head -n 10

        echo "Getting tool cache disk usage"
        du -shc "$AGENT_TOOLSDIRECTORY"/* | sort -hr | head -n 10

        echo "Disk usage inspection took $(($SECONDS - $start_time)) seconds"

    - name: Clean unneeded packages
      shell: bash
      run: |
        start_time=$SECONDS

        echo "Removing unneeded packages"
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"/Python
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"/CodeQL
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"/go
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"/PyPy

        echo "Package removal took $(($SECONDS - $start_time)) seconds"

    - name: Print final disk free space
      shell: bash
      run: |
        start_time=$SECONDS

        echo "Getting final disk free space"
        df -h

        echo "Final disk free space check took $(($SECONDS - $start_time)) seconds"