name: Test Firebase App Distribution
on:
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    environment: 'Development'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: curl -sL https://firebase.tools | bash
        name: Install Firebase CLI
      - shell: bash
        name: Upload dev apk to Firebase App Distribution
        env:
          FB_CREDENTIALS: ${{ secrets.FB_APP_DIST_CREDENTIALS }}
        run: |
          echo "$FB_CREDENTIALS" >> google_service_account2.json
          export GOOGLE_APPLICATION_CREDENTIALS=google_service_account2.json
          echo "google_service_account2.json contents"
          cat google_service_account2.json
          echo "google_service_account2.json file size"
          stat --format="%s" google_service_account2.json
          firebase --version
          firebase appdistribution:distribute temp/quickshop-dev-0.1.0.23.apk --debug --app ${{ vars.ANDROID_FIREBASE_APP_ID }} --release-notes "Initial dev build"
