
name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Run Flutter tests
        run: flutter test --coverage